### ISSUE TITLE
Не показывается статистика отдельных объявлений

### ISSUE THREAD

**Issue by untone-survive** [minimus/sam-pro-free-public#4]
После последнего обновления (1.9.5.65) не отображается статистика отдельных объявление на странице статистики.

При попытке развернуть место - ошибка 
`ej.stats.all.min.js?ver=13.1.0.21:formatted:1893 Uncaught TypeError: Cannot read property 'ejPvtData' of undefined`

![2016-09-29_02-22-26](https://cloud.githubusercontent.com/assets/1793309/18928802/df5affee-85eb-11e6-9099-a4113805e9aa.png)

**Comment by minimus** [comment]
Только в Хроме и появилась после последнего обновления оного... Работаю 
над этим вопросом...

**Comment by minimus** [comment]
Исправлено...
