### ISSUE TITLE
Неправильно отображается объявление по умолчанию для места.

### ISSUE THREAD

**Issue by untone-survive** [minimus/sam-pro-free-public#5]
1. Создаём место и задаём ему объявление по умолчанию (тип - изображение или код).
2. Добавляем объявление и прикрепляем его к созданному месту.
3. У объявления убираем галочку одобрено

![2016-10-18_01-37-54](https://cloud.githubusercontent.com/assets/1793309/19450427/9293f64c-94d3-11e6-8eef-cd1fae733d9f.png)
4. В админке в списке объявлений места видим, что объявление неактивно.

![2016-10-18_01-39-21](https://cloud.githubusercontent.com/assets/1793309/19450465/bbf8832c-94d3-11e6-90f7-0b9e2f20aaff.png)

На сайте объявление по умолчанию не отображается.

**Comment by minimus** [comment]
Спасибо за информацию.
Исправлено. Проверьте...
