### ISSUE TITLE
mcrypt is deprecated in PHP >= 7.1

### ISSUE THREAD

**Issue by schliflo** [minimus/sam-pro-free-public#6]
I'm testing with PHP7.1 and have been getting deprecation warnings. Sure they can be silenced, but it's probably best to look at this issue sooner rather than later as [mcrypt will be removed sometime soon](https://wiki.php.net/rfc/mcrypt-viking-funeral). I'ts used at least here: https://github.com/minimus/sam-pro-free-public/blob/master/sam-pro-front.php#L206

**Comment by minimus** [comment]
Resolved
